alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias open="mimeopen"
alias vi=vim
alias sqlite=sqlite3
alias sql=sqlite3
alias sq=sqlite3


alias gitclean='git branch --merged | egrep -v "(^\*|master|main|dev)" | xargs git branch -d'
alias gitcleansqmaster='git checkout -q master && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(gi    t merge-base master $branch) && [[ $(git cherry master $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]]     && git branch -D $branch; done'
alias gitcleansqmain='git checkout -q main && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(gi    t merge-base main $branch) && [[ $(git cherry main $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]]     && git branch -D $branch; done'

# copy onto clipboard 
alias copy="xclip -selection c"
# paste into terminal
alias paste="xclip -selection clipboard -o"
